### ISSUE TITLE
No clear error message with form with character in name column 

### ISSUE THREAD

**Issue by MappingKat** [Cadasta/cadasta-platform#1999]
1. Upload form. Have success.
[bad_character_form.xlsx](https://github.com/Cadasta/cadasta-platform/files/1745199/bad_character_form.xlsx)

2. open up ODK and try to download form. Get 500 error.

**Comment by alukach** [comment]
Error from the server:

```
2018-02-21 17:00:07,346 ERROR Internal Server Error: /collect/formList/dxgjn97c5cwtjzfrx77qyqhu/
Traceback (most recent call last):
  File "/opt/cadasta/env/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/cadasta/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/opt/cadasta/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/cadasta/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/opt/cadasta/env/lib/python3.5/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/opt/cadasta/env/lib/python3.5/site-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "./xforms/renderers.py", line 202, in render
    data.get('version'))
  File "./xforms/renderers.py", line 146, in insert_version_attribute
    root = etree.fromstring(xform)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:82934)
  File "src/lxml/parser.pxi", line 1819, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:124533)
  File "src/lxml/parser.pxi", line 1700, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:122964)
  File "src/lxml/parser.pxi", line 1040, in lxml.etree._BaseParser._parseUnicodeDoc (src/lxml/lxml.etree.c:116705)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:110510)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:112276)
  File "src/lxml/parser.pxi", line 613, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:111124)
  File "<string>", line None
lxml.etree.XMLSyntaxError: Failed to parse QName 'sda_date:', line 1, column 1038
```

The error occurs in the renderer when we attempt to generate an XML object from a string:

https://github.com/Cadasta/cadasta-platform/blob/d663f5d9f5ee8ce39894ad4caed1331c54e1b7e7/cadasta/xforms/renderers.py#L144-L146

This is called by the `XFormDownloadView ` view:

https://github.com/Cadasta/cadasta-platform/blob/d663f5d9f5ee8ce39894ad4caed1331c54e1b7e7/cadasta/xforms/views/api.py#L151-L166

This is likely far too late to be catching errors. This is a problem with our validation within the serializer that accepts an uploaded `Questionnaire`.  Ideally, we should be validating the `Questionnaire` for its capabilities to be returned with this renderer at time of upload.
