### ISSUE TITLE
Form Submission Will Not Parse

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#366]
I filled out a few instances of a form and uploaded. One won't submit. The XML is available [here](https://drive.google.com/a/cadasta.org/file/d/0B6yvvj_4PdlPUEpYeEEyQzFWTG8/view?usp=sharing). Have not been able to reproduce so far.  

```
Traceback (most recent call last):
  File "/opt/cadasta/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/cadasta/env/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/cadasta/env/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/cadasta/env/lib/python3.5/site-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/cadasta/env/lib/python3.5/site-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/opt/cadasta/env/lib/python3.5/site-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "/vagrant/cadasta/xforms/views/api.py", line 35, in create
    data = serializer.save()
  File "/opt/cadasta/env/lib/python3.5/site-packages/rest_framework/serializers.py", line 191, in save
    self.instance = self.create(validated_data)
  File "/vagrant/cadasta/xforms/serializers.py", line 46, in create
    create_models = model_helper.add_data_to_models(survey)
  File "/vagrant/cadasta/xforms/mixins/model_helper.py", line 24, in add_data_to_models
    location = self.add_data_to_spatial_unit(data, project)
  File "/vagrant/cadasta/xforms/mixins/model_helper.py", line 42, in add_data_to_spatial_unit
    geometry=self._format_geometry(data['location_geometry']),
  File "/vagrant/cadasta/xforms/mixins/model_helper.py", line 88, in _format_geometry
    float(point.split(' ')[0])]
ValueError: could not convert string to float: 
```

**Comment by linzjax** [comment]
Latest push to feature/xform branch should fix this
