### ISSUE TITLE
Error running manage.py loadpolicies

### ISSUE THREAD

**Issue by karenc** [Cadasta/cadasta-platform#836]
### Steps to reproduce the error

I was trying to load some test data in my development site.  Following the instructions on the [dev wiki](https://devwiki.corp.cadasta.org/Loading%20test%20data), I tried to run `python manage.py loadpolicies` and got a `KeyError`.

### Actual behavior

```console
$ python manage.py loadpolicies 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/karen/cadasta/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/karen/cadasta/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/karen/cadasta/env/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/karen/cadasta/env/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/karen/cadasta-platform/cadasta/accounts/management/commands/loadpolicies.py", line 10, in handle
    load.run(force=options['force'], update=options['update'])
KeyError: 'force'
```

### Expected behavior

The command should finish successfully without errors.

**Comment by karenc** [comment]
This is probably more of an error on the dev wiki, I guess it should probably say:

```
python manage.py loadstatic
python manage.py loadfixtures
```

If you don't think we ever need to run `loadpolicies` on its own, feel free to close this.
